[package]
name = "view-titxt"
version = "0.1.0"
authors = ["Rubens Brandao <git@rubens.io>"]
edition = "2021"

[dependencies]
binaryninja = { path = "../../rust" }
log = "*"

[lib]
crate-type = ["cdylib"]

[profile.release]
panic = "abort"
lto = true
debug = 1
