[package]
name = "decompile"
version = "0.1.0"
authors = ["Fabian Freyer <mail@fabianfreyer.de>"]
edition = "2021"

[dependencies]
binaryninja = {path="../../"}
clap = { version = "3.0", features = ["derive"] }

