[package]
name = "arch_msp430"
version = "0.1.0"
authors = ["jrozner"]
edition = "2021"

[dependencies]
binaryninja = { path = "../../rust" }
log = "0.4"
msp430-asm = "^0.2"

[lib]
crate-type = ["cdylib"]

[profile.release]
panic = "abort"
lto = true
debug = 1
