[package]
name = "binaryninja-derive"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = "2.0"
quote = "1"
proc-macro2 = "1.0"
proc-macro2-diagnostics = { version = "0.10", default-features = false }

[lib]
proc-macro = true
