[package]
name = "dwarf_export"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
binaryninja = {path="../../../"}
binaryninjacore-sys = {path="../../../binaryninjacore-sys"}
gimli = "^0.31"
log = "^0.4"
object = { version = "0.32.1", features = ["write"] }
