#pragma once

#include "binaryninjaapi.h"
#include "armv7.h"

#define IL_FLAG_N 0
#define IL_FLAG_Z 2
#define IL_FLAG_C 4
#define IL_FLAG_V 6
#define IL_FLAG_Q 8

#define IL_FLAGWRITE_NONE 0
#define IL_FLAGWRITE_ALL 1
#define IL_FLAGWRITE_NZ 2
#define IL_FLAGWRITE_CNZ 3
#define IL_FLAGWRITE_FLOAT_COMPARE 4

struct decomp_result;

enum Armv7Intrinsic : uint32_t
{
	ARMV7_INTRIN_DBG,
	ARMV7_INTRIN_DMB_SY,
	ARMV7_INTRIN_DMB_ST,
	ARMV7_INTRIN_DMB_ISH,
	ARMV7_INTRIN_DMB_ISHST,
	ARMV7_INTRIN_DMB_NSH,
	ARMV7_INTRIN_DMB_NSHST,
	ARMV7_INTRIN_DMB_OSH,
	ARMV7_INTRIN_DMB_OSHST,
	ARMV7_INTRIN_DSB_SY,
	ARMV7_INTRIN_DSB_ST,
	ARMV7_INTRIN_DSB_ISH,
	ARMV7_INTRIN_DSB_ISHST,
	ARMV7_INTRIN_DSB_NSH,
	ARMV7_INTRIN_DSB_NSHST,
	ARMV7_INTRIN_DSB_OSH,
	ARMV7_INTRIN_DSB_OSHST,
	ARMV7_INTRIN_ISB,
	ARMV7_INTRIN_YIELD,
	ARMV7_INTRIN_MRS,
	ARMV7_INTRIN_MSR,
	ARMV7_INTRIN_VMRS,
	ARMV7_INTRIN_VMSR,
	ARMV7_INTRIN_SEV,
	ARMV7_INTRIN_HVC,
	ARMV7_INTRIN_SMC,
	ARMV7_INTRIN_WFE,
	ARMV7_INTRIN_WFI,
	ARMV7_INTRIN_HINT,
	ARMV7_INTRIN_UNPREDICTABLE,
	ARM_M_INTRIN_SET_BASEPRI,
	// Following names are from Table D17-2 of ARM DDI 0406C.d, changed  from
	// CamelCase to UPPERCASE with underscores preserved and ARMV7_INTRIN_ prefixed.
	ARMV7_INTRIN_COPROC_GETONEWORD, // MRC, MRC2
	ARMV7_INTRIN_COPROC_GETTWOWORDS, // MRRC, MRRC2
	ARMV7_INTRIN_COPROC_SENDONEWORD, // MCR, MCR2
	ARMV7_INTRIN_COPROC_SENDTWOWORDS, // MCRR, MCRR2
	ARMV7_INTRIN_COPROC_STORE, // STC, STC2, STCL, STC2L
	ARMV7_INTRIN_COPROC_LOAD, // LDC, LDC2, LDCL, LDC2L
	ARMV7_INTRIN_COPROC_DATAPROCESSING, // CDP, CDP2

	ARMV7_INTRIN_EXCLUSIVE_MONITORS_PASS,
	ARMV7_INTRIN_SET_EXCLUSIVE_MONITORS,
	ARMV7_INTRIN_CPS,
	ARMV7_INTRIN_CPSID,
	ARMV7_INTRIN_CPSIE,
	ARMV7_INTRIN_SETEND,
	ARMV7_INTRIN_CLREX,
	ARMV7_INTRIN_PLD,
	ARMV7_INTRIN_CRC32B,
	ARMV7_INTRIN_CRC32CB,
	ARMV7_INTRIN_CRC32CH,
	ARMV7_INTRIN_CRC32CW,
	ARMV7_INTRIN_CRC32H,
	ARMV7_INTRIN_CRC32W,
	ARMV7_INTRIN_SEL,
	ARMV7_INTRIN_QADD,
	ARMV7_INTRIN_QSUB,
	ARMV7_INTRIN_QDADD,
	ARMV7_INTRIN_QDSUB,
	ARMV7_INTRIN_QADD16,
	ARMV7_INTRIN_QADD8,
	ARMV7_INTRIN_QSUB16,
	ARMV7_INTRIN_QSUB8,
	ARMV7_INTRIN_UQADD16,
	ARMV7_INTRIN_UQADD8,
	ARMV7_INTRIN_UQSUB16,
	ARMV7_INTRIN_UQSUB8,
	ARMV7_INTRIN_SXTAB16,
	ARMV7_INTRIN_SXTB16,
	ARMV7_INTRIN_UXTAB16,
	ARMV7_INTRIN_UXTB16,
	ARMV7_INTRIN_SADD16,
	ARMV7_INTRIN_SADD8,
	ARMV7_INTRIN_SHADD16,
	ARMV7_INTRIN_SHADD8,
	ARMV7_INTRIN_UHADD16,
	ARMV7_INTRIN_UHADD8,
	ARMV7_INTRIN_SASX,
	ARMV7_INTRIN_UASX,
	ARMV7_INTRIN_SHASX,
	ARMV7_INTRIN_UHASX,
	ARMV7_INTRIN_SSAX,
	ARMV7_INTRIN_USAX,
	ARMV7_INTRIN_SSUB16,
	ARMV7_INTRIN_SSUB8,
	ARMV7_INTRIN_SHSUB8,
	ARMV7_INTRIN_SHSUB16,
	ARMV7_INTRIN_UHSUB8,
	ARMV7_INTRIN_UHSUB16,
	ARMV7_INTRIN_USUB8,
	ARMV7_INTRIN_USUB16,
	ARMV7_INTRIN_SMLAD,
	ARMV7_INTRIN_SMLADX,
	ARMV7_INTRIN_SMUAD,
	ARMV7_INTRIN_SMUADX,
	ARMV7_INTRIN_SMUSD,
	ARMV7_INTRIN_SMUSDX,
	ARMV7_INTRIN_SMLSD,
	ARMV7_INTRIN_SMLSDX,
	ARMV7_INTRIN_SMLSLD,
	ARMV7_INTRIN_SMLSLDX,
	ARMV7_INTRIN_SMLAWB,
	ARMV7_INTRIN_SMLAWT,
	ARMV7_INTRIN_SMLALD,
	ARMV7_INTRIN_SMLALDX,
	ARMV7_INTRIN_USAD8,
	ARMV7_INTRIN_USADA8,
	ARMV7_INTRIN_QSAX,
	ARMV7_INTRIN_UQASX,
	ARMV7_INTRIN_UQSAX,
	ARMV7_INTRIN_VRINTA,
	ARMV7_INTRIN_VMAXNM,
	ARMV7_INTRIN_VMINNM,
	ARMV7_INTRIN_VMAX,
	ARMV7_INTRIN_VMIN,
	ARMV7_INTRIN_VPMAX,
	ARMV7_INTRIN_VPMIN,
	ARMV7_INTRIN_VREV16,
	ARMV7_INTRIN_VREV32,
	ARMV7_INTRIN_VREV64,
	ARMV7_INTRIN_VEXT,
	ARMV7_INTRIN_VCGT,
	ARMV7_INTRIN_VCEQ,
	ARMV7_INTRIN_VTBL,
	ARMV7_INTRIN_VTBX,
	ARMV7_INTRIN_VDUP,
	ARMV7_INTRIN_VABD,
	ARMV7_INTRIN_VABDL,
	ARMV7_INTRIN_VABA,
	ARMV7_INTRIN_VABAL,
	ARMV7_INTRIN_VADDL,
	ARMV7_INTRIN_VADDW,
	ARMV7_INTRIN_VRADDHN,
	ARMV7_INTRIN_VRSHR,
	ARMV7_INTRIN_VRSHL,
	ARMV7_INTRIN_VSRA,
	ARMV7_INTRIN_VRSRA,
	ARMV7_INTRIN_VSRI,
	ARMV7_INTRIN_VSLI,
	ARMV7_INTRIN_VLD2,
	ARMV7_INTRIN_VLD4,
	ARMV7_INTRIN_VST2,
	ARMV7_INTRIN_VST4,
	ARMV7_INTRIN_VSHL,
	ARMV7_INTRIN_VSHR,
	ARMV7_INTRIN_VSHLL,
	ARMV7_INTRIN_VBIF,
	ARMV7_INTRIN_VBIT,
	ARMV7_INTRIN_VBSL,
	ARMV7_INTRIN_VQADD,
	ARMV7_INTRIN_VHADD,
	ARMV7_INTRIN_VQSHL,
	ARMV7_INTRIN_VQRSHL,
	ARMV7_INTRIN_VQSHRN,
	ARMV7_INTRIN_VQSHRUN,
	ARMV7_INTRIN_VQRSHRN,
	ARMV7_INTRIN_VQRSHRUN,
	ARMV7_INTRIN_VQMOVN,
	ARMV7_INTRIN_VQMOVUN,
	ARMV7_INTRIN_VMLA,
	ARMV7_INTRIN_VMLS,
	ARMV7_INTRIN_VMLAL,
	ARMV7_INTRIN_VMLSL,
	ARMV7_INTRIN_VMUL,
	ARMV7_INTRIN_VQDMULL,
	ARMV7_INTRIN_SSAT,
	ARMV7_INTRIN_SSAT16,
	ARMV7_INTRIN_USAT,
	ARMV7_INTRIN_USAT16,
	ARMV7_INTRIN_SRS,
	ARMV7_INTRIN_RFE,
	ARMV7_INTRIN_UADD16,
	ARMV7_INTRIN_UADD8,
	ARMV7_INTRIN_SMLABB,
	ARMV7_INTRIN_SMLABT,
	ARMV7_INTRIN_SMLATB,
	ARMV7_INTRIN_SMLATT,
	ARMV7_INTRIN_VADD,
	ARMV7_INTRIN_VSUB,
	ARMV7_INTRIN_VRHADD,
	ARMV7_INTRIN_VRECPE,
	ARMV7_INTRIN_VABS,
	ARMV7_INTRIN_VCVT_FIXED,
	ARMV7_INTRIN_VABS_Q,
	ARMV7_INTRIN_VCVT_FIXED_Q,
	// Lane-wise >=; matching lanes produce all ones, otherwise all zeros.
	ARMV7_INTRIN_VCGE,
	ARMV7_INTRIN_VCGE_Q,
	ARMV7_INTRIN_VCGT_Q,
	// Lane-wise < comparison, with the original source operand order.
	ARMV7_INTRIN_VCLT,
	ARMV7_INTRIN_VCLT_Q,
	// Widen each D-register lane to twice its size in a Q register.
	ARMV7_INTRIN_VMOVL,
	// Keep the low half of each Q-register lane in a D register.
	ARMV7_INTRIN_VMOVN,
	// Widening products from D sources to Q; index 0xff selects vector-by-vector multiplication.
	// Polynomial size=64 is ARMv8 VMULL.P64: one carryless 64x64 product with a 128-bit result.
	ARMV7_INTRIN_VMULL,
	// Lane-wise negation; integer results wrap to the element size without saturation.
	ARMV7_INTRIN_VNEG,
	ARMV7_INTRIN_VNEG_Q,
	// Adjacent pair sums from source1 fill the low half, then source2 the high half.
	// Integer sums wrap to the element size; floating sums use standard SIMD FP behavior.
	ARMV7_INTRIN_VPADD,
	// Register VSHL uses the signed low byte of each count lane: negative shifts right.
	// Signedness controls right-shift fill; large counts zero or sign-fill each lane.
	ARMV7_INTRIN_VSHL_Q,
	// Immediate VSHL applies one count to every lane, without saturation.
	ARMV7_INTRIN_VSHL_IMM,
	ARMV7_INTRIN_VSHL_IMM_Q,
	ARMV7_INTRIN_VSHR_Q,
	// Logical right shift of Q source lanes, then truncate each to half its width in D.
	// The size parameter is the source lane width (16, 32, or 64 bits).
	ARMV7_INTRIN_VSHRN,
	// Transpose adjacent lane pairs, reading both sources before writing either result.
	// Result 1 interleaves even lanes of source1/source2; result 2 interleaves odd lanes.
	// The size parameter is the lane width in bits (8, 16, or 32).
	ARMV7_INTRIN_VTRN,
	ARMV7_INTRIN_VTRN_Q,
	// For each 8/16/32-bit lane, return all ones if (source1 & source2) != 0, else zero.
	ARMV7_INTRIN_VTST,
	ARMV7_INTRIN_VTST_Q,
	// De-interleave the concatenation of source1 (low) and source2 (high).
	// Result 1 contains even lanes, result 2 odd lanes, in their original order.
	// Lane width is 8/16 bits for D and 8/16/32 bits for Q; both inputs are read before either write.
	ARMV7_INTRIN_VUZP,
	ARMV7_INTRIN_VUZP_Q,
	// Interleave source1/source2 lanes, preserving their order, then split the result.
	// Result 1 is the low half, result 2 the high half; read both inputs before either write.
	// Lane width is 8/16 bits for D and 8/16/32 bits for Q.
	ARMV7_INTRIN_VZIP,
	ARMV7_INTRIN_VZIP_Q,
};

enum ArmFakeRegister: uint32_t
{
	FAKEREG_SYSCALL_INFO = armv7::REG_INVALID+1
};

bool GetLowLevelILForArmInstruction(BinaryNinja::Architecture* arch, uint64_t addr,
    BinaryNinja::LowLevelILFunction& il, armv7::Instruction& instr, size_t addrSize);
bool GetLowLevelILForThumbInstruction(BinaryNinja::Architecture* arch,
    BinaryNinja::LowLevelILFunction& il, decomp_result *instr, bool ifThenBlock = false);
void SetupThumbConditionalInstructionIL(BinaryNinja::LowLevelILFunction& il, BinaryNinja::LowLevelILLabel& trueLabel,
    BinaryNinja::LowLevelILLabel& falseLabel, uint32_t cond);
BinaryNinja::ExprId GetCondition(BinaryNinja::LowLevelILFunction& il, uint32_t cond);
