BINJA_API_INC_PATH = ..\..\ 
BINJA_API_LIB = ..\..\bin\libbinaryninjaapi.lib
BINJA_CORE_LIB = "c:\Program Files\Vector35\BinaryNinja\binaryninjacore.lib"

FLAGS = /DWIN32 /D__WIN32__ /EHsc /I$(BINJA_API_INC_PATH) /link $(BINJA_API_LIB) $(BINJA_CORE_LIB)

print_syscalls: ./src/arm-syscall.cpp
	if not exist bin mkdir bin
	cl ./src/arm-syscall.cpp $(FLAGS) /Fe:.\bin\print_syscalls
